### ISSUE TITLE
popBackStack on Start Destination is leading to a Blank Screen.

### ISSUE THREAD

**Issue by AmniX** [raamcosta/compose-destinations#109] opened 2022-04-20 19:49 UTC
Hey. 
Hope you are well.
So On my Start Destination, I've a Toolbar which have a back button. It's leading me to a Empty Blank Screen.
So far i tried to clear then Back Stack till root but that too is not working for me. 

Could you provide your input here?

**Comment by AmniX** [comment] 2022-04-20 19:52
For now, I'm using `LocalOnBackPressedDispatcherOwner.current?.onBackPressedDispatcher?.onBackPress()` for expected result.

**Comment by raamcosta** [comment] 2022-04-20 19:54
The expected result being closing the app, correct?

**Comment by raamcosta** [comment] 2022-04-20 19:54
What version are you using?

**Comment by AmniX** [comment] 2022-04-20 19:56
> The expected result being closing the app, correct?

So compose is being used by a separate activity, so expected result is to close that activity.

> What version are you using?

Latest, `1.5.1-beta`

**Comment by raamcosta** [comment] 2022-04-20 20:04
Have you tried `navigateUp` instead of `popBackStack` ?

**Comment by raamcosta** [comment] 2022-04-20 20:05
I'm pretty sure this is not related with Compose Destinations, it should either be expected behaviour or a bug with Jetpack Compose Navigation.

I'll take a look though 🙂

**Comment by AmniX** [comment] 2022-04-20 20:05
> Have you tried `navigateUp` instead of `popBackStack` ?

Yes. Nothing happened with that. not even the blank screen.

**Comment by AmniX** [comment] 2022-04-20 20:05
> I'm pretty sure this is not related with Compose Destinations, it should either be expected behaviour or a bug with Jetpack Compose Navigation.
> 
> I'll take a look though 🙂

Okay. Let me know here as well please. Thank you. Good work though :)

**Comment by raamcosta** [comment] 2022-04-21 19:56
Tried with a minimal official jetpack compose navigation sample and it also happens like this.
So it really is not related to Compose Destinations 🙂 

Btw, as a side note, usually back buttons on the app, should use `navigateUp` instead of `popBackStack`. With either of those you can check if they return false, and if they do, you know navigation was not successful (which is the case here, I also tested that).

I'll close it, but feel free to add follow up below 🙂

**Closed by raamcosta** 2022-04-21 19:56 UTC
Labels: dependency

**Comment by walaankit** [comment] 2022-09-08 06:38
@AmniX @raamcosta I was also facing a similar issue with navigateUp not working with the root destination... and this is expected behaviour and what I found from the official documentation. 

https://developer.android.com/guide/navigation/navigation-navigate#back-stack

**Comment by raamcosta** [comment] 2022-09-08 08:03
Yes, I know this 🙂 this is part of the difference between navigateUp and popBackStack

**Comment by extmkv** [comment] 2022-10-17 19:29
@raamcosta just to clarify, you managed to replicate the issue but isn't related with compose destinations?

**Comment by raamcosta** [comment] 2022-10-17 21:39
Correct. Seems like it’s expected behaviour. But as I said above, use navigateUp instead 🙂

**Comment by extmkv** [comment] 2022-10-18 05:57
Yes, the part I'm aware of, but I still have the same issue using `navigateUp`.

**Comment by raamcosta** [comment] 2022-10-18 06:59
That’s weird. I remember testing this and navigateUp was returning false 🤔

**Comment by extmkv** [comment] 2022-10-18 07:45
It returns `false`, the issue is that the composable still visible on screen, and the activity open.

A bit more information about the scenario:
- The Composable is the `start` defined as `@RootNavGraph(start = true)
- Composable has an arrow that calls the `navigateUp`
- Compose still visible after calling the `navigateUp`,  touch interaction isn't working after that.

**Comment by gastsail** [comment] 2023-03-24 19:09
Ok, so for me, what it was is that if you have inside a viewmodel a state lets say "PasswordResetEvent" and then you emit that to propagate a navcontroller.popBackstack() it will maybe send that event multiple times making your entry destination as blank and you will not see anything, I tried with navigateUp and its working fine but its really annoying that the NavHost re-executes these extra recompositions when the transition happens between these two destinations.

**Comment by GazimSoliev** [comment] 2023-06-26 17:29
I have the same problem when send popBackStack using SharedFlow

**Comment by jd1378** [comment] 2023-09-06 13:14
I experience the blank screen issue when I quickly press back button when the page is still transitioning 
I don't think this is supposed to happen

**Comment by slaviboy** [comment] 2023-12-09 02:04
In my case I was emitting the same  Result.Success, twice very fast: one after another
- first time from cache
- second time after API call

----

To fix it I set second argument for navigate() method to `true`:
```
navigator.navigate(
       DrumPadComposableDestination(audioZipState.data),
       true
 )
```
