### ISSUE TITLE
Getting IllegalDestinationsSetup: NavGraph 'RootNavGraph' doesn't have any start route

### ISSUE THREAD

**Issue by nrobi144** [raamcosta/compose-destinations#219] opened 2022-08-16 13:55 UTC
I'm getting `IllegalDestinationsSetup: NavGraph 'RootNavGraph' doesn't have any start route. Use corresponding annotation with start = true in the Destination or nested NavGraph you want to be the start of this graph!`

**Version**: `1.6.15-beta`

**Context:** I have a multi-module setup and I'm using my own `@CustomNavGraph`s, so no `@Destination` uses `@RootNavGraph`

**Workaround:** Adding a
```
@Composable
@RootNavGraph(start = true)
@Destination()
fun Empty() {
}
```
seems to fix the false compilation error

**Full stack-trace:** 
```
[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: NavGraph 'RootNavGraph' doesn't have any start route. Use corresponding annotation with `start = true` in the Destination or nested NavGraph you want to be the start of this graph!
	at com.ramcosta.composedestinations.codegen.commons.ModuleOutputUtilsKt.startingDestination(ModuleOutputUtils.kt:40)
	at com.ramcosta.composedestinations.codegen.writers.sub.NavGraphsSingleObjectWriter.write(NavGraphsSingleObjectWriter.kt:55)
	at com.ramcosta.composedestinations.codegen.writers.ModuleOutputWriter.write(ModuleOutputWriter.kt:39)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:43)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:48)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:237)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:235)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:330)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:235)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:264)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:255)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:157)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1642)
	at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

**Comment by raamcosta** [comment] 2022-08-17 20:59
Hi @nrobi144  👋 

Could you please give a bit more context? Do any of your custom NavGraph annotations use `default = true`? Is there some `@Destination` with no annotation for the NavGraph it belongs to?

Also, you say you have a multi module setup, but I see in the stack trace that the `NavGraphsSingleObjectWriter` is working which means you have the default ksp configuration in build.gradle. Do you have all destinations in the same module or are they spread in different modules?

**Comment by raamcosta** [comment] 2022-08-17 20:59
oops, reopening

**Comment by nrobi144** [comment] 2022-08-18 06:39
Hey @raamcosta 

Yes, so I have the following structure:
- `module A -> shared/base module`, `module B -> shared/base module`

`shared/base module` has `arg("compose-destinations.mode", "navgraphs")`. All 3 modules (A, B, base) have their custom `@XYNavGraph()` with one `start = true` destination and all `@Destination` s belong to either module A, B or base

**Comment by raamcosta** [comment] 2022-08-18 07:33
Thank you! It seems to me that ksp task thinks some Destination either from module A or B belongs to RootNavGraph. 
This can happen if your XYNavGraph doesn’t specify `@NavGraph(default = true)` and there is some destination without any NavGraph annotation(if you don’t specify nav graph it will use the default which by default is RootNavGraph).

Please confirm if that is the case. Looking at the code I don’t see any issue here, but ofc I may be  overlooking something 😅

**Comment by raamcosta** [comment] 2022-08-18 07:35
Btw given your setup, which module calls DestinationsNavHost? A or B or both? Or some other that depends on both?

**Comment by nrobi144** [comment] 2022-08-18 11:13
> if your XYNavGraph doesn’t specify @NavGraph(default = true) and there is some destination without any NavGraph annotation(if you don’t specify nav graph it will use the default which by default is RootNavGraph).

Just verified this. So
- Adding `@NavGraph(default = true)` to either A, B or shared/base modules didn't fix the issue
- Also all `@Destination`s are annotated with one of my `@XYCustomNavGraph`s

**Comment by nrobi144** [comment] 2022-08-18 11:14
Both A and B specify their own `DestinationsNavHost`, they are different apps, `base/shared` being the SDK

**Comment by raamcosta** [comment] 2022-08-18 18:32
Hmm @nrobi144 in which module did you wrote the workaround?

```kotlin
@Composable
@RootNavGraph(start = true)
@Destination()
fun Empty() {
}
```

And can you please open the NavGraphs generated object of that same module and paste it here? Thanks!

**Comment by nrobi144** [comment] 2022-08-19 08:51
@raamcosta both A and B. There is no `NavGraphs` object generated
![Screenshot 2022-08-19 at 11 51 16](https://user-images.githubusercontent.com/68047666/185582363-8c79c647-0d6f-469e-ab36-c6c46ca40696.png)

**Comment by raamcosta** [comment] 2022-08-19 09:08
Really? 🤔
The crash comes from the class that generates NavGraphs. I think A and B modules are using the default mode which should generate NavGraphs object.
Do modules A and B use some ksp configuration in gradle files?

**Comment by nrobi144** [comment] 2022-08-19 13:14
Nope, neither A nor B have a ksp configuration added in gradle.

Also some really weird behaviour, my `@SharedNavGraph` results generated Graph class with either the name `SharedGraph` or `SharedNavGraph`. So I have to rename imports after every clean build or so

**Comment by raamcosta** [comment] 2022-08-19 18:27
> @raamcosta both A and B. There is no `NavGraphs` object generated ![Screenshot 2022-08-19 at 11 51 16](https://user-images.githubusercontent.com/68047666/185582363-8c79c647-0d6f-469e-ab36-c6c46ca40696.png)

> Nope, neither A nor B have a ksp configuration added in gradle.

I am now checking the code. If A and B don't have any ksp configuration, then NavGraphs object must be generated. Is it possible that when you were checking for it you did not see it because the last time ksp run it stopped due to the above IllegalDestinationsSetup exception? It must be something like this, I really don't see how NavGraphs wouldn't be generated..

**Comment by raamcosta** [comment] 2022-08-19 18:41
> Also some really weird behaviour, my @SharedNavGraph results generated Graph class with either the name SharedGraph or SharedNavGraph. So I have to rename imports after every clean build or so

This one is even more of a headscratcher 🤔
Do you have `compose-destinations.moduleName` config for this module (I guess shared module) ?

**Comment by raamcosta** [comment] 2022-08-21 17:55
Found the issue @nrobi144 and @sobaya-0141.

Sorry for this, it was a regression in 1.6.14. It will be fixed in the coming days.

**Closed** 2022-08-21 22:55 UTC
Labels: bug

**Comment by raamcosta** [comment] 2022-08-21 23:26
Done! 1.x.16 should be up any minute now on maven central. @nrobi144 please confirm everything runs smoothly now 🙂

**Comment by nrobi144** [comment] 2022-08-22 08:22
Great work @raamcosta , yes it works!
