### ISSUE TITLE
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

### ISSUE THREAD

**Issue by deividas717** [raamcosta/compose-destinations#526] opened 2023-10-13 15:53 UTC
When adding a `ResultRecipient` to composable screen I'm getting error `Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option`

Here's the screenshot of generated Screen Destination

<img width="1206" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/12860841/e5a9c574-d4ce-40b5-a4c4-62b50bfa3eeb">

If `ResultRecipient` is removed, everythig compiles

app.gradle file

```
 compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
```

**Comment by raamcosta** [comment] 2023-10-14 23:21
Hi!

Hmmm 🤔 
I need to take some time to analyse this properly, I have never seen it before.
I'll mark it also for v2.
Until then, try targetting java 11, that probably fixes it.

**Comment by deividas717** [comment] 2023-10-15 11:39
Hi!
Thanks for a reply.
Sadly targeting java 11 does not helped. I got same error.

**Comment by hristogochev** [comment] 2023-10-17 23:11
Hello! I stumbled upon the same issue and after switching to java 11 I had to invalidate the caches of Android Studio, that fixed it.

**Comment by deividas717** [comment] 2023-10-18 17:13
> Hello! I stumbled upon the same issue and after switching to java 11 I had to invalidate the caches of Android Studio, that fixed it.

Thank you! Now it works perfectly! :)

**Comment by dave08** [comment] 2023-12-18 12:28
It seems like according to: https://developer.android.com/build/jdks#compileSdk java 11 is only supported on Android api 32 and above, we need to support from api level 21... would it be possible to use 

```
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
```
to compile this library?

**Comment by raamcosta** [comment] 2023-12-18 13:09
We are using this library at work and our min sdk is 24. We’re also targeting Java 11 with no issue.

I will be checking this later on, but for now I’m not considering this urgent since I believe it works with all min sdk that compose also requires.

**Comment by raamcosta** [comment] 2023-12-18 13:10
But @dave08 if you find any issue with your min sdk please do let me know 🙂

**Comment by dave08** [comment] 2023-12-18 13:46
@raamcosta Compose supports from sdk 21...

**Comment by raamcosta** [comment] 2023-12-28 01:11
Hi guys! 

After some tests I did find that my understanding of these jvm targets was off, apologies 🙏 

1.9.56 is cooking where this should be fixed. Thank you for reporting 🙇

**Closed** 2023-12-28 01:10 UTC
Labels: v2.0

**Comment by UKMIITB** [comment] 2024-01-16 10:00
@raamcosta 
Can you share your analysis of JVM 17
We are using following configuration in our app

compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    
And our app support is 21 & above. And the app seems to be working fine.

**Comment by raamcosta** [comment] 2024-01-16 10:04
Are you using desugaring? It seems to be related.
To be completely honest, I am not sure I fully understand all the implications here, but I was able to reproduce the reported issue and then I was able to fix it in the library.
