### ISSUE TITLE
Dialog style destination not available after navigating away from it

### ISSUE THREAD

**Issue by dpredovic** [raamcosta/compose-destinations#78] opened 2022-03-26 10:50 UTC
If I try to navigate like:

Default1 -> Dialog1 -> Dialog2 and then navigateBack to Dialog1 it's gone and user is presented with Default1
Dafault1 -> Dialog1 -> Default2 and then navigateBack to Dialog1 it's gone and user is presented with Default1
Default1 -> Dialog1 -> BottomSheet1 and then navigateBack to Dialog1 works

**Comment by raamcosta** [comment] 2022-03-28 11:53
Hi @dpredovic!

Thank you for reporting.
Interesting, I just tested this and I only have an issue with the "Default1 -> Dialog1 -> Default2" case. All others are working as you expect them to.

Anyway, I don't think this is something that can be easily fixed by this library. It seems like an issue with official Compose Navigation (which we use behind the scenes), unless this is somehow intended? I'm honestly not sure, even though that would be weird to me.

**Comment by raamcosta** [comment] 2022-03-28 13:40
So turns out this is expected.
I found this about the non compose navigation and it feels like the same reasons are going to be valid for Compose too. If nothing else, they probably want to keep the same behavior as before.

https://stackoverflow.com/questions/67237079/how-to-prevent-bottomsheetdialogfragment-from-dismissing-after-a-navigation-to-a

So, just to be clear, this is the expected behaviour:
1- **Default1 -> Dialog1 -> Dialog2/BottomSheet1**: Dialog1 is kept on the back stack. (I did find an issue with passing results back from Dialog2 to Dialog1 which I will be fixing soon, thanks for that btw 🙂 )
2- **Default1 -> BottomSheet1 -> Dialog1/BottomSheet2**: Same as above.
3- **Default1 -> Dialog1/BottomSheet1 -> Default2**: Dialog1/BottomSheet1 is popped from the back stack when you navigate to Default2.

**Closed by raamcosta** 2022-03-28 13:40 UTC
Labels: wontfix, dependency issue
