### ISSUE TITLE
Deprecation warnings in UUIDNavType (Serializable / Parcelable)

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#274] opened 2022-10-24 08:58 UTC
Right now the library generates code that is deprecated since API 33

Full generated code (for example with UUID):
```kotlin
val uUIDNavType = UUIDNavType(UUIDNavTypeSerializer)

class UUIDNavType(
    private val stringSerializer: DestinationsNavTypeSerializer<UUID>
) : DestinationsNavType<UUID?>() {

    override fun get(bundle: Bundle, key: String): UUID? {
        return bundle.getSerializable(key) as UUID?
    }

    override fun put(bundle: Bundle, key: String, value: UUID?) {
        bundle.putSerializable(key, value)
    }

    override fun parseValue(value: String): UUID? {
        return if (value == DECODED_NULL) {
            null
        } else {
            stringSerializer.fromRouteString(value)       
        }
    }

    override fun serializeValue(value: UUID?): String {
        return if (value == null) {
            ENCODED_NULL
        } else {
            encodeForRoute(stringSerializer.toRouteString(value))
        }
    }

    override fun get(navBackStackEntry: NavBackStackEntry, key: String): UUID? {
        return navBackStackEntry.arguments?.getSerializable(key) as? UUID?
    }

    override fun get(savedStateHandle: SavedStateHandle, key: String): UUID? {
        return savedStateHandle.get(key)
    }
}
```

Solution:
If targetSDK = 33, generate the following code:
```kotlin
bundle.getSerializable(key, UUID::class) // for API 33 only, for API < 33 generate the same code.

// helper
@Suppress("DEPRECATION")
inline fun <reified T : Serializable> Bundle.serializable(key: String) =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU)
        getSerializable(key, T::class.java)
    else getSerializable(key) as T?

inline fun <reified T : Serializable> Intent.serializable(key: String) = extras?.serializable<T>(key)
```

Same applies for Parcelable

**Comment by raamcosta** [comment] 2022-10-24 22:02
This is duplicate of https://github.com/raamcosta/compose-destinations/issues/262

Let me know if the conclusion there doesn't work for you. For now only 1.7+ have these suppressed (which is enough imo, no need to change all the generated code, it works just as well).

**Closed by raamcosta** 2022-10-24 22:02 UTC

**Comment by Nek-12** [comment] 2022-10-25 00:32
I'm not using 1.7.22 due to #221

**Comment by raamcosta** [comment] 2022-10-25 07:32
1.7.23 is coming later today 🙂

**Comment by raamcosta** [comment] 2022-10-25 21:25
1.7.23-beta soon on maven central!
