### ISSUE TITLE
Re-render of DestinationsNavHost from ViewModel value

### ISSUE THREAD

**Issue by r1nalds** [raamcosta/compose-destinations#527] opened 2023-10-19 21:57 UTC
Hello! I am enjoying your navigation library and it is really helpful, but I have ran into an issue where I have created an Onboarding screen with data save to a DataStore instance. 

Whenever "isOnboardingComplete" is true, ViewModel returns a different screen (Locations) which should launch and display first in this case...but it isn't. It displays the RootNavGraph(start = true) page which is the Onboarding screen, but then it gets a value of the Location screen from the ViewModel and starts to re-render the DestinationsNavHost with the new value and causes a weird animation from top-left corner to the center.

I didn't experience this behaviour with Navigatio Compose, when "isOnboardingComplete" is true, it only displays the correct screen which is the Locations screen without any bugs and visible UI issues.

Hope you can help me with this, cause your library is awesome!

Here is my code for some context.

PreferencesViewModel: 

```kotlin
class PreferencesViewModel @Inject constructor(
    private val preferencesRepository: PreferencesRepository
): ViewModel() {
    private val  _onboardingStatus: MutableLiveData<Boolean> = MutableLiveData()
    val onboardingStatus: LiveData<Boolean> = _onboardingStatus

    private val _isloading: MutableState<Boolean> = mutableStateOf(true)
    val isLoading: State<Boolean> = _isloading

    private val _startDestination: MutableState<Destination> = mutableStateOf(OnboardingScreenDestination)
    val startDestination: State<Destination> = _startDestination
    init {
        viewModelScope.launch {
            preferencesRepository.getOnboardingStatus().collect { completed ->
                if (completed) {
                    _startDestination.value = LocationsScreenDestination
                }
            }
            _isloading.value = false
        }
    }
  
}
```

OnboardingViewModel:
```kotlin
@HiltViewModel
class OnboardingViewModel @Inject constructor(
    private val preferencesRepository: PreferencesRepository
) : ViewModel() {
    fun markOnboardingStatusCompleted() = viewModelScope.launch {
        preferencesRepository.markOnboardingStatusCompleted()
    }
}
```

MainActivity:
```kotlin
@AndroidEntryPoint
![output-onlinegiftools (1)](https://github.com/raamcosta/compose-destinations/assets/76100574/ba660279-208a-4749-8e1c-3e727e209491)

class MainActivity : ComponentActivity() {
    @Inject
    lateinit var viewModel: PreferencesViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        installSplashScreen().setKeepOnScreenCondition{
            !viewModel.isLoading.value
        }
        setContent {
            SchneiderSecurityTheme {
                val screen by viewModel.startDestination
                val navController = rememberNavController()
                DestinationsNavHost(navGraph = NavGraphs.root, navController = navController, startRoute = screen)
            }
        }
    }
}
```

My suspicions are that when onboardingStatus is true, the code executes like this:

onCreate -> DestinationsNavHost with Onboarding Screen (which is the default value in VM and RootNavGraph(start = true) -> Whenever value gets read in a viewmodel, it passes back to the MainActivity with Locations Screen, then it re-renders with a weird animation from the top-left to the center
![output-onlinegiftools (1)](https://github.com/raamcosta/compose-destinations/assets/76100574/ddf73b75-41b8-4627-8862-d4fea897673d)

**Comment by r1nalds** [comment] 2023-10-20 16:55
I might have found something!

This same behaviour is observed on Navigation Compose version 2.7.4 using Navigation Compose approach of navigation. Changing to a version 2.5.0-alpha02 and launching the app, it executes perfectly as it should.

Somewhere between Navigation Compose 2.5.0-alpha02 and Navigation Compose  2.7.4 has broken something.

So this is not your libary's fault.

This is the video I'm checking out for Navigation Compose way of navigating from Onboarding screen - https://www.youtube.com/watch?v=6dRwaXH2cYA (And this is the behaviour I want using your library, but your library uses the 2.7.2 version of Navigation Compose, which for me is broken)

Maybe you can look into this and see what is happening behind all the code? If this is fixed, I'm going back to your library. For now I will use Navgigation Compose.

Thank you so much!

**Comment by srenrd** [comment] 2023-10-26 11:07
Hi, i ran into the same issue. However i found that it can be resolved by assuring your current view has the fillMaxSize modifier. When this exact modifier is missing it will course a animation on transitions. Added it removes the animation. No idea why Google decided to change this.

**Comment by TomBell-Trove** [comment] 2024-01-19 02:39
I'm also suffering from this. In the past I was able to fix via fillMaxSize but now it doesn't seem to have any impact. 

I have a dashboard with a `DestinationsNavHost` with a graph containing three screens. If I navigate to it with a command to immediately select one of the non-default screens I get the top-left corner slide in animation. Applying fillMaxSize to literally everything half fixes it; instead of the corner, it expands in size from the centre.  

If I defer the navigation by 100ms the issue is resolved which makes me think it's to do with the order of composition

**Comment by raamcosta** [comment] 2024-03-12 00:23
I remember some release notes of official library regarding this, so hopefully all works well now.
Do try to fillMaxSize, so that the animation isn't about screen size changes.

**Closed by raamcosta** 2024-03-12 00:23 UTC
