### ISSUE TITLE
Crash - IllegalStateException: LayoutNode should be attached to an owner

### ISSUE THREAD

**Issue by MichaelOliveiraBx** [raamcosta/compose-destinations#512] opened 2023-09-07 09:37 UTC
Hi
first of all I wanted to thank you for this framework which is well developed and very practical.
We have just move our entire navigation application and thanks to your library, it was much simpler.

We're making a [sample](https://github.com/omada-game/AndroidNavigationSample) to manage all the cases we had to test before starting to port our app.
We're making it available to other people who might find it helpful.
The concepts we tested are:
- Top navigation for fullscreen
- A bottom bar navigation
- Have Modal Bottom Sheet
- Module management
- Deeplinks with a provider (AppsFlyers) which forces us to do the navigation by hand

We have little hope that you will see where it might come from but we never know.

We have a crash since we put the navigation, very random (not able to reproduce locally), and which is in the run loop of draw of the frame, and therefore we lose all notion of our code to have origin.

Does this crash already speak to you ?

And another thing, do you see how we could add logs or debug information in the node compose so that we can know a little better where the crash comes from ?

Thank you very much in advance

```
java.lang.IllegalStateException: LayoutNode should be attached to an owner
        at androidx.compose.ui.node.LayoutNodeKt.requireOwner(LayoutNode.kt:1448)
        at androidx.compose.ui.node.LayoutNode.invalidateSemantics$ui_release(LayoutNode:412)
        at androidx.compose.ui.node.SemanticsModifierNodeKt.invalidateSemantics(SemanticsModifierNode.kt:92)
        at androidx.compose.foundation.text.modifiers.TextStringSimpleNode.doInvalidations(TextStringSimpleNode:171)
        at androidx.compose.foundation.text.modifiers.TextStringSimpleElement.update(TextStringSimpleElement.kt:56)
        at androidx.compose.foundation.text.modifiers.TextStringSimpleElement.update(TextStringSimpleElement.kt:33)
        at androidx.compose.ui.node.NodeChainKt.updateUnsafe(NodeChainKt:808)
        at androidx.compose.ui.node.NodeChainKt.access$updateUnsafe(NodeChainKt:1)
        at androidx.compose.ui.node.NodeChain.updateNode(NodeChain.kt:653)
        at androidx.compose.ui.node.NodeChain.updateFrom$ui_release(NodeChain:138)
        at androidx.compose.ui.node.LayoutNode.setModifier(LayoutNode.kt:844)
        at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode:47)
        at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:47)
        at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(ComposerImpl:1712)
        at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1710)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer:625)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
        at android.view.Choreographer.doFrame(Choreographer.java:998)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8296)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by raamcosta** [comment] 2023-09-09 10:14
Hi @MichaelOliveiraBx ! 👋 

Thank you for choosing this lib, you'll have a good time :). Any issue you guys have, I'll be sure to tackle quickly!

Unfortunately I do not know what could be the cause of this crash, but I can tell you I really don't think it's related with this library 🤔 
Does it happen on a specific screen? Can you infer anything else from the logs about what kind of situations it happens in?

**Comment by raamcosta** [comment] 2023-10-14 23:25
Closing this one.

**Closed by raamcosta** 2023-10-14 23:25 UTC
Labels: question
