### ISSUE TITLE
Generated code isn't immediately available after build

### ISSUE THREAD

**Issue by davidliu** [raamcosta/compose-destinations#457] opened 2023-07-02 16:56 UTC
Not sure if the bug is with this library or KSP or Android Studio, but it seems to take a while (a couple minutes) before the newly generated code is reflected in Android Studio.

The files are there immediately after a build if I view it on the filesystem, but don't seem to appear in the build folder on Android Studio, and references are similarly unavailable.

Android Studio version: Android Studio Flamingo | 2022.2.1
KSP version: 1.8.20-1.0.10
Android Build Tools gradle plugin: 8.0.2

**Comment by raamcosta** [comment] 2023-07-09 15:49
I honestly don't think this is caused by this library unfortunately 😬 

For me it sometimes takes some action to refresh like deleting the import and adding it again, or similar, but it's not always. Most times it works like you'd expect it to.

**Comment by raamcosta** [comment] 2023-07-23 09:45
I'm closing this as it's not caused by this library. Let me know if it has improved a bit with newer versions of KSP / IDE.

**Closed by raamcosta** 2023-07-23 09:45 UTC
