### ISSUE TITLE
Generates empty navDeepLink block when BuildConfig field is used in the path

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#285] opened 2022-11-06 10:11 UTC
### Reproducer:  
```
class Deeplinks {
 companion object {
        const val SCHEMA = BuildConfig.DEEPLINK_SCHEMA
        const val PATH = BuildConfig.DEEPLINK_PATH
    }
}

@Composable
@RootNavGraph(start = true)
@Destination(
    deepLinks = [
        DeepLink(
            uriPattern = "${Deeplinks.SCHEMA}://$FULL_ROUTE_PLACEHOLDER",
            action = Intent.ACTION_VIEW
        )
    ],
)
internal fun Home(nav: AppNavigator) {
    HomeScreen(nav)
}
```

### Generated class:  
```
internal object HomeDestination : NavigationDirectionDestination {
         
    public operator fun invoke(): Direction  = this
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute: String = "home"

    override val route: String = baseRoute
    
	override val deepLinks: List<NavDeepLink> get() = listOf(
		navDeepLink {
			action = "android.intent.action.VIEW"
			// no urlPattern here 
		}
	)

    @Composable
    override fun DestinationScope<Unit>.Content(
		dependenciesContainerBuilder: @Composable DependenciesContainerBuilder<Unit>.() -> Unit
    ) {
		val dependencyContainer = remember { DestinationDependenciesContainer(this) }
		dependencyContainer.apply { dependenciesContainerBuilder() }

		Home(
			nav = dependencyContainer.require()
		)
    }
}
```

### Expected:  
App launches fine, navigates to the deeplink using specified uri

### Actual:  
App crashes on start with
```
java.lang.IllegalArgumentException: Deep link null can't be used to open destination Destination(0x115d6ebb) route=home
```

### Workaround:  

Hardcode the values

**Comment by Nek-12** [comment] 2022-11-06 10:36
I did not experience this problem when my Deeplinks class was in another module. As soon as I moved it to be in the same module as my navigation code, the problem appeared.

**Comment by raamcosta** [comment] 2022-11-06 10:47
Thanks @Nek-12 , however this is already reported: https://github.com/raamcosta/compose-destinations/issues/178

The reason is that BuildConfig seems to be generated after ksp, so when ksp reads the value it doesn't exist. So if you use a different module, if that module is a dependency, it is generated first, and then it works.

**Comment by raamcosta** [comment] 2022-11-06 10:48
Closing since it's a duplicate of https://github.com/raamcosta/compose-destinations/issues/178

@Nek-12 If you could please add the relevant info to that issue instead? Thanks 🙏

**Closed by raamcosta** 2022-11-06 10:48 UTC
