### ISSUE TITLE
Using nested graph for a bottom bar destination recreates its VM on each display

### ISSUE THREAD

**Issue by StephenVinouze** [raamcosta/compose-destinations#237] opened 2022-09-12 06:49 UTC
Hi there 👋
This might be a mere misconception of mine but I wanted to pick your brain on this. Let's say you have a bottom bar with three destinations (for instance A, B, C). There are attached to the same nav graph (root to make things simpler). B is declared in a nested graph that is embedded in route so that some destination starting from B cannot be started from another screen.

We would have something like this:
```
DestinationsNavHost(/*...*/) {
    bottomBarGraph()
}

fun ManualComposableCallsBuilder.bottomBarGraph() {
    composable(ADestination) { A() }
    BGraph()
    composable(ADestination) { C() }
}

fun ManualComposableCallsBuilder.BGraph() {
    composable(BDestination) {
        BScreen(
            onClick = {
                destinationsNavigator.navigate(DDestination)
            },
        )
    }
    D() // Launched only from B
}
```

As for the B composable and its declaration with its nav graph, we would have this:

```
@BNavGraph(start = true)
@Destination
@Composable
fun BScreen(
    viewModel: BVM = hiltViewModel()
)

@RootNavGraph
@NavGraph
annotation class BNavGraph(
    val start: Boolean = false
)
```

**Observed:**
The B VM attached to the B composable is always recreated when navigated to the B destination from the bottom bar.

**Expected:**
The B VM should be scoped to the bottom bar graph (aka root) so that it doesn't get recreated, just like it's the case for A and C (that also have their own VM).

I was under the impression that created a custom nested graph linked to the Root nav graph would make that link but that doesn't seem the case. Or maybe I'm misusing the nested graph in that specific case. My understanding is that nested graph allows me to split my navigation into smaller chunks for readability but also to make sure that some destinations stay scoped within a nav graph – especially if I'd modularize my app. Does this make sense to you? Btw I only use one NavHost 🙂

Thanks again for your great work and eager to get some feedback from you 🙏

**Comment by raamcosta** [comment] 2022-09-13 09:52
Hi @StephenVinouze 

How are you navigating to these screens / popping them from the back stack?
Can you show me that code? 🙂 

If you do just this to get the VM `viewModel: BVM = hiltViewModel()` then it means the VM is scoped to the NavBackStackEntry and as soon as that is popped up from back stack, VM goes away.

If you want to scope the VM to a particular nav graph, check this:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels/#share-viewmodels-between-multiple-destinations

Obviously, in your case you'd be passing those VMs directly by manually calling the Composable screens, but the idea is the same to ge the VM scoped to a nav graph.

**Comment by StephenVinouze** [comment] 2022-09-13 10:29
Those VM have no to be shared in that case (I actually had that use case last time I reached out to you and successfully got it working).
I feel it's more a conception issue here on my end but wanted to better understand it. 
I have one NavHost for the app that handles the navigation/popping. My root graph is attached to it. A have a first screen that displays a bottom bar with 3 screens A, B , C. From the B screen you can show other screens that can only be navigated to from B screen.
Naively, I wanted to create a nested graph to isolate this nav portion from the rest by declaring a nav graph for B (attached to root nav graph as shown above) and where I would declare the composable and direction in the `ManualComposableCallsBuilder ` from there.
However, it seems that declaring a nav graph for B screen detaches this screen from the bottom bar graph that holds the screen VM i memory.
Maybe I just need to create the sub graph with the `ManualComposableCallsBuilder` without creating a nested nav graph 🤔 
I don't see any other code to share since all is handled in the navigation composable where I've extracted the interesting part above to show my use case.
Hoping this make more sense to you :)

**Comment by raamcosta** [comment] 2022-09-13 15:34
Yes, it does. But just to reiterate, the way you're getting the ViewModel scopes it to the Destination (or NavBackStackEntry, in this case we can use both terms). So if that Destination is popped from the back stack, then the VM goes away, and when navigating back to it, it will create a new one.
You can scope it to the RootGraph if you want, but that means the VM will be alive throughout the whole process (since all screens belong to root graph).

So, if you're saying that adding B as a nested graph causes this behaviour (I didn't know either), it must mean that it does that because now B destination is getting popped from back stack.

I've used this piece of code for debugging (it uses a restricted Api, so don't use this in production):

```
LaunchedEffect(navController) {
    navController.addOnDestinationChangedListener { _, _ ,_ ->
        navController.backQueue.print()
    }
}


// .... the print function:

fun ArrayDeque<NavBackStackEntry>.print(prefix: String = "stack") {
    val stack = toMutableList()
        .map { it.appDestination().javaClass.simpleName + "@" + it.toString().split("@")[1] }
        .toTypedArray().contentToString()
    println("$prefix = $stack")
}
```

Try adding this and observing when B Destination is added to the back stack and when it goes away. Also, the "@" above ensures if you have multiple B Destinations on the back stack, each will have a different hash so you can follow them easily.

Let me know the output of this 🙂

**Comment by StephenVinouze** [comment] 2022-09-14 14:32
```
So, if you're saying that adding B as a nested graph causes this behaviour (I didn't know either), it must mean that it does that because now B destination is getting popped from back stack.
```
Yes definitively. Just need to know what does that now. I've tried your piece of code but I can't get past a NPE within the `destination()` method due to a null `NavGraphRegistry[this]`

**Comment by raamcosta** [comment] 2022-09-14 14:34
Do it after calling DestinationsNavHost sorry 😅

**Comment by StephenVinouze** [comment] 2022-09-15 05:58
Hmm I still couldn't make it work 🤔 I've put the side effect just after declaring the DestinationsNavHost. And also tried to defer the effect within the B screen but it crashes as soon as I open it.

**Comment by raamcosta** [comment] 2022-09-15 17:59
I can reproduce it, but it seems like NavBackStackEntry doesn't have routes (like wtf?!, I thought this was only nullable because of when using it from fragments navigation)

Ok, this is interesting, let me get back to you 🙂

**Comment by raamcosta** [comment] 2022-09-15 18:02
Oh! No actually when parent is null, as in, if we try to get destination for a nav graph 🤯 

I definitely need to do some changes here, glad you found this! 🙏

**Comment by raamcosta** [comment] 2022-09-15 18:32
btw, in the mean time, just do this:

```kotlin
fun ArrayDeque<NavBackStackEntry>.print(prefix: String = "STACK!!") {
    val stack = toMutableList()
        .map { it.destination.route + "@" + it.toString().split("@")[1] }
        .toTypedArray().contentToString()
    println("$prefix = $stack")
}
```

**Comment by StephenVinouze** [comment] 2022-09-16 05:57
Didn't do much but glad it helped spotted a hidden issue 😅 Thxs for the workaround. To be fair I first thought about this but I wasn't sure if printing the route directly would have an unwanted effect than intereacting with the graph registry. I'll try that out!

**Comment by Tomasan7** [comment] 2022-09-18 10:17
Hi, I just wanted to add my own observations experiencing the same problem.

I have a DestinationsNavHost nested into RootNavHost using it's NavGraph. When I use `hiltViewModel()` in the destination, a new instance of the ViewModel is returned each time navigating to that destination. But when I press back, it navigates back to the last destination which actually uses the already created viewmodel instance.

**Comment by raamcosta** [comment] 2022-09-18 10:22
Hey @Tomasan7 👋

Exactly that is expected. If you navigate to a specific destination it’s like navigating to a new instance of the same fragment and new fragment instance = new back stack entry = new view model.
If you want to have a single destination of that particular type you can navigate with singleTop = true (from memory, it can be slightly different).
This is the same thing you can observe with all official jetpack navigation libraries, no matter if they’re compose based or not.

Hope that makes sense 🙂

**Comment by Tomasan7** [comment] 2022-09-18 11:09
Aha, sorry in that case.
Anyway do you know how would I accomplish, so that the first time I navigate to the destination a new ViewModel instance is created and then each time navigating to it again uses the same ViewModel?

**Comment by raamcosta** [comment] 2022-09-18 11:20
Like I said with singleTop option. It’s part of a lambda in the navigate method. You can quickly find it if you search for it 🙂

**Comment by raamcosta** [comment] 2022-09-18 11:20
It’s the same way as with official library

**Comment by Tomasan7** [comment] 2022-09-18 11:44
Using the following:
```kotlin
contentNavController.navigate(item.destination.route) {
  launchSingleTop = true
}
```
unfortunately doesn't work. (nothing changes, new instance still gets created)

**Comment by raamcosta** [comment] 2022-09-18 14:08
I don’t know exactly what you want to achieve but singleTop makes it so that if you already have that as the top destination on the back stack, it doesn’t make a new one.
Maybe what you want to achieve is this?

https://stackoverflow.com/questions/60927327/create-only-one-instance-of-fragment-while-navigating-to-destinationsandroid

check second answer and adapt it to pass a Destination instead of the id of one.

You have to remember that we have a stack and we cannot move some destination to the top without popping all others in between 🙂

**Comment by Tomasan7** [comment] 2022-09-18 14:32
That is almost it, but not fully.
I will rather ask somewhere else, since I already clutter this thread with unrelated things. Thanks for help :)

**Comment by raamcosta** [comment] 2022-09-18 21:10
No problem, you're welcome!

**Comment by raamcosta** [comment] 2022-09-20 06:48
Thanks @StephenVinouze 

So.. a couple of interesting things (at least this is my immediate reaction):
- How come A isn’t popped when you navigate to others but the others are?
- How the hell do you get the same VM instance for C even after C is popped from the back stack and recreated? 
- B VM to me is acting normally, I wouldn’t expect the same instance to be kept really. But then again I don’t understand how that is happening with C.

Can you please:

1. Share the code where you’re doing the navigation when a bottom bar item is clicked.
2. Confirm that your C VM is not tied to the activity or root graph? Share also the code you’re using to get the VM. 

If I’m wrong here, I definitely need to do some sample app to investigate further, but if you could provide this it would maybe be easier 🙂

**Comment by StephenVinouze** [comment] 2022-09-20 07:20
Here is the code when clicking on a bottom bar item:
```
navController.navigate(destination.route) {
    popUpTo(navController.graph.findStartDestination().id) {
        saveState = true
    }
    launchSingleTop = true
    restoreState = true
}
```
As you can see, the VM is kept because of the `saveState` and `restoreState` setup (that's the recommended setup from the [compose navigation docs](https://developer.android.com/jetpack/compose/navigation#bottom-nav). A doesn't get popped because we pop to the start destination of the current graph to prevent stacking all screens in the backstack when navigating with the bottom bar items.

All my VMs attached to the screens in this example are scoped to their destination by using the `hiltViewModel()` creation method. So each destination as a VM parameter that defaults to `hiltViewModel()`

```
@Composable
fun CScreen(
    viewModel: CViewModel = hiltViewModel(),
) {}
```

My take is that creating a nested graph messes up with the `saveState` and `restoreState` properties somehow.

**Comment by raamcosta** [comment] 2022-10-02 21:08
Hey @StephenVinouze !

So sorry it took me so long to look into this 😞 

I have a very small project where I tried to recreate your scenario and I can see that the VMs get reused indeed (🤯  need to follow this up with someone since I don't understand how it is possible) but I also have that for the bottom bar item tied to the nested graph. So for me it is consistent regardless of the route is for a given destination or a nested nav graph.

I managed to do everything in the same file, which is great for this :D 
Check it out here 👇 

```kotlin
package com.ramcosta.composedestinationstesting

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.material.BottomNavigation
import androidx.compose.material.BottomNavigationItem
import androidx.compose.material.Button
import androidx.compose.material.Icon
import androidx.compose.material.Scaffold
import androidx.compose.material.Text
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.filled.Settings
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.navigation.NavBackStackEntry
import androidx.navigation.NavController
import androidx.navigation.NavGraph.Companion.findStartDestination
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import com.ramcosta.composedestinations.DestinationsNavHost
import com.ramcosta.composedestinations.annotation.Destination
import com.ramcosta.composedestinations.annotation.NavGraph
import com.ramcosta.composedestinations.annotation.RootNavGraph
import com.ramcosta.composedestinations.navigation.DestinationsNavigator
import com.ramcosta.composedestinationstesting.destinations.HomeScreenDestination
import com.ramcosta.composedestinationstesting.destinations.ProfileScreenDestination
import com.ramcosta.composedestinationstesting.destinations.SettingsScreenDestination
import com.ramcosta.composedestinationstesting.ui.theme.ComposeDestinationsTestingTheme
import dagger.hilt.android.AndroidEntryPoint
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject

@AndroidEntryPoint
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ComposeDestinationsTestingTheme {

                val navController = rememberNavController()

                Scaffold(
                    bottomBar = {
                        BottomBar(navController)
                    }
                ) {
                    DestinationsNavHost(
                        navController = navController,
                        navGraph = NavGraphs.root,
                        modifier = Modifier.padding(it)
                    )

                    LaunchedEffect(navController) {
                        navController.addOnDestinationChangedListener { _, _ ,_ ->
                            navController.backQueue.print()
                        }
                    }

                }
            }
        }
    }

}

enum class BottomDestination(
    val direction: String,
    val icon: ImageVector,
    val label: String
) {
    Home(HomeScreenDestination.route, Icons.Default.Home, "Home"),
    Profile(ProfileScreenDestination.route, Icons.Default.Person, "Profile"),
    Settings(NavGraphs.settingsGraph.route, Icons.Default.Settings, "Settings")
}

@Composable
private fun BottomBar(
    navController: NavController
) {
    val currentDestination by navController.currentBackStackEntryAsState()

    BottomNavigation {
        BottomDestination.values()
            .forEach {
                BottomNavigationItem(
                    selected = it.direction == currentDestination?.destination?.route,
                    onClick = {
                        navController.navigate(it.direction) {
                            popUpTo(navController.graph.findStartDestination().id) {
                                saveState = true
                            }
                            launchSingleTop = true
                            restoreState = true
                        }
                    },
                    icon = {
                        Icon(
                            imageVector = it.icon,
                            contentDescription = it.label
                        )
                    },
                    label = { Text(it.label) },
                )
            }
    }
}

fun ArrayDeque<NavBackStackEntry>.print(prefix: String = "stack") {
    val stack = toMutableList()
        .map { it.destination.route + "@" + it.toString().split("@")[1] }
        .toTypedArray().contentToString()
    println("$prefix = $stack")
}

@RootNavGraph(start = true)
@Destination
@Composable
fun HomeScreen(
    navigator: DestinationsNavigator,
    vm: HomeViewModel = hiltViewModel()
) = Column {
    println("vm = ${vm.toString().replace("com.ramcosta.composedestinationstesting.", "")}")

    Text(text = "Hello!")

    Button(
        onClick = { navigator.navigate(ProfileScreenDestination) }
    ) {
        Text("Go to Profile!")
    }

    Button(
        onClick = { navigator.navigate(SettingsScreenDestination) }
    ) {
        Text("Go to Settings!")
    }
}

@Destination
@Composable
fun ProfileScreen(
    vm: ProfileViewModel = hiltViewModel()
) {
    println("vm = ${vm.toString().replace("com.ramcosta.composedestinationstesting.", "")}")
    Text(text = "PROFILE SCREEN")

}

@SettingsGraph(start = true)
@Destination
@Composable
fun SettingsScreen(
    vm: SettingsViewModel = hiltViewModel()
) {
    println("vm = ${vm.toString().replace("com.ramcosta.composedestinationstesting.", "")}")
    Text(text = "SETTINGS SCREEN")
}

@RootNavGraph
@NavGraph
annotation class SettingsGraph(
    val start: Boolean = true
)


@HiltViewModel
class ProfileViewModel @Inject constructor(): ViewModel() {

    override fun onCleared() {
        println("vm cleared = ${this.toString().replace("com.ramcosta.composedestinationstesting.", "")}")
    }
}

@HiltViewModel
class SettingsViewModel @Inject constructor(): ViewModel() {

    override fun onCleared() {
        println("vm cleared = ${this.toString().replace("com.ramcosta.composedestinationstesting.", "")}")
    }
}

@HiltViewModel
class HomeViewModel @Inject constructor(): ViewModel() {

    override fun onCleared() {
        println("vm cleared = ${this.toString().replace("com.ramcosta.composedestinationstesting.", "")}")
    }
}
```

**Comment by raamcosta** [comment] 2022-11-17 22:21
@StephenVinouze Have you had the chance of checking my latest comment?

**Comment by StephenVinouze** [comment] 2022-11-18 18:43
Nope was pretty busy sorry. I should have time next week to sample this.

**Comment by StephenVinouze** [comment] 2022-11-24 14:38
Ah! I took over your sample (thanks for creating it) and I've found out why I had this issue :) 
When declaring the screen's route (in the enum class in your sample), I was using the generated screen route instead of the `NavGraph` route. I assumed wrongly it was the same but it has a perverse impact.

In your sample, you have this which gives the expected behavior:
```
enum class BottomDestination(
    val direction: String,
    val icon: ImageVector,
    val label: String
) {
    Home(HomeScreenDestination.route, Icons.Default.Home, "Home"),
    Profile(ProfileScreenDestination.route, Icons.Default.Person, "Profile"),
    Settings(NavGraphs.settingsGraph.route, Icons.Default.Settings, "Settings")
}
```

While I declared it like this:
```
enum class BottomDestination(
    val direction: String,
    val icon: ImageVector,
    val label: String
) {
    Home(HomeScreenDestination.route, Icons.Default.Home, "Home"),
    Profile(ProfileScreenDestination.route, Icons.Default.Person, "Profile"),
    Settings(SettingsScreenDestination.route, Icons.Default.Settings, "Settings")
}
```
Subtle difference right? :)

Output is:
```
stack = [root@ae6302af, home_screen@59faf6ba]
vm = HomeViewModel@2fe5f8
Installing profile for com.example.myapplication
stack = [root@ae6302af, home_screen@59faf6ba, settings_graph@77623a0, settings_screen@3210acc9]
vm = SettingsViewModel@f6ec8a1
stack = [root@ae6302af, home_screen@59faf6ba, profile_screen@58788e55]
vm = ProfileViewModel@9f91c4f
stack = [root@ae6302af, home_screen@59faf6ba, settings_graph@dd3cca7a, settings_screen@586fe31c]
vm = SettingsViewModel@b96616e
stack = [root@ae6302af, home_screen@59faf6ba, profile_screen@c99968e5]
vm = ProfileViewModel@9f91c4f
```
The `SettingsViewModel` gets recreated.

Do you think it's an issue on your end? Or should we always use the `NavGraph` and it's just something I didn't understand while using nested graphs?

**Comment by raamcosta** [comment] 2022-11-24 14:55
Hmm that's interesting.. to me it just made sense since we wanted to tie the bottom bar item to the nav graph. But I don't know why it happens, I just know it's not specific to compose destinations 😄 
We're not doing anything special to this functionality, we'll have the same behavior with official libraries.

**Comment by raamcosta** [comment] 2022-12-03 16:53
Given my our last comments, I think we can close this. It was a good learning exercise for sure! 
Thanks @StephenVinouze !

**Closed by raamcosta** 2022-12-03 16:53 UTC
Labels: question
