### ISSUE TITLE
Render Issue in animations

### ISSUE THREAD

**Issue by mohsen2986** [raamcosta/compose-destinations#343] opened 2023-01-26 16:06 UTC
Hey
Im using animation between my navigations , but it not work as i expected
here is sniped of my code

create transition
```object SplashTransitions : DestinationStyle.Animated {
    override fun AnimatedContentScope<NavBackStackEntry>.exitTransition(): ExitTransition? {
        return when (targetState.appDestination()) {
            SplashScreenDestination ->
                return slideOutVertically (
                    targetOffsetY = { -it / 2 },
                    animationSpec = tween(2000)
                )
            else -> null
        }
    }
```

and use here
```
@Destination(
    style = SplashTransitions::class,
    start = true ,
)
@Composable
fun SplashScreen(
    navigator: DestinationsNavigator ,
)
```

but animation render like this

https://user-images.githubusercontent.com/33317132/214885229-59b69cda-8302-4bdf-a0be-9b3f52354630.mp4

the splash screen must go up but not worked!
i tested another animations for `enterTransition` on other screens and it work! 
even i try this animation with **accompanist-navigation-animation** and it works fine.

**Comment by raamcosta** [comment] 2023-02-05 14:50
Hi @mohsen2986 !

Cna you please send me working code with accompanist? I find this really weird since on our side we're not doing much here, just passing whatever animations back to the accompanist APIs.
So I'm guessing when you're rewriting the animation stuff with compose destinations, you're probably missing some small detail.

**Comment by raamcosta** [comment] 2023-03-25 11:58
Hey @mohsen2986 !

Any chance I can get a sample with accompanist working well? And the same sample with this library not working? I cannot reproduce this so I'm affraid I can't help much without these.

**Comment by raamcosta** [comment] 2023-04-07 09:04
Closing this for lack of reply. Let me know if you can provide a sample like I said in previous comment.

**Closed by raamcosta** 2023-04-07 09:04 UTC
Labels: help wanted
