### ISSUE TITLE
Using DestinationWrap for Permissions Crash

### ISSUE THREAD

**Issue by hscissors** [raamcosta/compose-destinations#362] opened 2023-02-17 21:37 UTC
I'm trying to add a destination wrapper that checks for permissions before showing the next destination (in my case it's a bottom sheet)

If I put the `screenContent` of the `DestinationWrapper` in a `Column`, I can get the permissions to show, but when they are approved for the first time, the app crashes with the error below. Once the have been granted, if I go through the same flow it works as expected. 

`versions.compose_destinations = "1.8.33-beta"`
`versions.accompanist = "0.28.0"`
`versions.compose = "1.3.2"`

```
FATAL EXCEPTION: main
Process: com.x.x.x, PID: 11438
java.util.NoSuchElementException: Key Expanded is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:349)
	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetAnchorChangeHandler$1.onAnchorsChanged(ModalBottomSheet.kt:671)
	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetAnchorChangeHandler$1.onAnchorsChanged(ModalBottomSheet.kt:670)
	at androidx.compose.material.SwipeableV2Kt$swipeAnchors$2.invoke-ozmzZPI(SwipeableV2.kt:123)
	at androidx.compose.material.SwipeableV2Kt$swipeAnchors$2.invoke(SwipeableV2.kt:108)
	at androidx.compose.material.SwipeAnchorsModifier.onRemeasured-ozmzZPI(SwipeableV2.kt:632)
	at androidx.compose.ui.node.BackwardsCompatNode.onRemeasured-ozmzZPI(BackwardsCompatNode.kt:414)
	at androidx.compose.ui.node.NodeCoordinator.onMeasured(NodeCoordinator.kt:311)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:159)
	at androidx.compose.foundation.layout.OffsetPxModifier.measure-3p2s80s(Offset.kt:200)
	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:319)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:319)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
	at androidx.compose.foundation.layout.SizeModifier.measure-3p2s80s(Size.kt:781)
	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:319)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1090)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1086)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:107)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1086)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:342)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1156)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1147)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:309)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:434)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:39)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:330)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:795)
	at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:216)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1025)
	at android.view.View.draw(View.java:22647)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21475)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21475)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21475)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21475)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21475)
	at android.view.View.draw(View.java:22375)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22647)
	at com.android.internal.policy.DecorView.draw(DecorView.java:820)
	at android.view.View.updateDisplayListIfDirty(View.java:21519)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4421)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4149)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3309)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by raamcosta** [comment] 2023-02-26 22:09
Hi @hscissors !

It's kinda hard for me to be sure of anything here. Can you get me a minimal sample that reproduces the issue? Thanks.

Keep in mind however, my feature simply calls the Wrap Composable method with the `screenContent` composable lambda.. I don't believe this can be something caused by the library (although I could be wrong).

**Comment by raamcosta** [comment] 2023-03-25 12:32
Hi @hscissors!

Can you help ☝️ ?

**Comment by hscissors** [comment] 2023-03-25 14:54
It ended up being that the composable function annotated with BottomSeetDestination cannot be empty. 

We had a loading state that didn't render anything, and then a data state which had some Compose UI structures. So the loading caused the crash.

**Comment by raamcosta** [comment] 2023-03-25 14:57
So should I close this issue? Or do you still think there is something to improve in the lib?

**Closed** 2023-04-07 09:03 UTC
Labels: help wanted
